import {
  Atom,
  Boxes,
  Braces,
  Database,
  Gauge,
  Inbox,
  Layers,
  type LucideIcon,
  Mail,
  MousePointer2,
  Palette,
  Route,
  Server,
  Shapes,
  ShieldCheck,
  TestTube,
  Zap,
} from "lucide-react";

export const stackIcons: Record<string, LucideIcon> = {
  React: Atom,
  TypeScript: Braces,
  Vite: Zap,
  "Tailwind CSS v4": Palette,
  "Redux Toolkit": Boxes,
  "TanStack Query": Database,
  "React Router": Route,
  "Lucide React": Shapes,
  Vitest: TestTube,
  Playwright: MousePointer2,
  Bun: Zap,
  Elysia: Server,
  Zod: Braces,
  "Drizzle ORM": Layers,
  PostgreSQL: Database,
  Redis: Gauge,
  Nodemailer: Mail,
  Mailpit: Inbox,
  "Session + CSRF security": ShieldCheck,
};

export const capabilities = [
  "capability1",
  "capability2",
  "capability3",
  "capability4",
  "capability5",
  "capability6",
] as const;
export const frontendStack = [
  ["React", "react", "https://github.com/facebook/react"],
  ["TypeScript", "typescript", "https://github.com/microsoft/TypeScript"],
  ["Vite", "vite", "https://github.com/vitejs/vite"],
  ["Tailwind CSS v4", "tailwind", "https://github.com/tailwindlabs/tailwindcss"],
  ["Redux Toolkit", "redux", "https://github.com/reduxjs/redux-toolkit"],
  ["TanStack Query", "query", "https://github.com/TanStack/query"],
  ["React Router", "router", "https://github.com/remix-run/react-router"],
  ["Lucide React", "lucide", "https://github.com/lucide-icons/lucide"],
  ["Vitest", "vitest", "https://github.com/vitest-dev/vitest"],
  ["Playwright", "playwright", "https://github.com/microsoft/playwright"],
] as const;
export const backendStack = [
  ["Bun", "bun", "https://github.com/oven-sh/bun"],
  ["Elysia", "elysia", "https://github.com/elysiajs/elysia"],
  ["Zod", "zod", "https://github.com/colinhacks/zod"],
  ["Drizzle ORM", "drizzle", "https://github.com/drizzle-team/drizzle-orm"],
  ["PostgreSQL", "postgres", "https://github.com/postgres/postgres"],
  ["Redis", "redis", "https://github.com/redis/redis"],
  ["Nodemailer", "nodemailer", "https://github.com/nodemailer/nodemailer"],
  ["Mailpit", "mailpit", "https://github.com/axllent/mailpit"],
  ["Session + CSRF security", "security"],
  ["Vitest", "apiTests", "https://github.com/vitest-dev/vitest"],
] as const;
